Microsoft Windows [Version 10.0.18362.418]
(c) 2019 Microsoft Corporation. All rights reserved.

C:\Users\r40815014>python
Python 3.7.2 (tags/v3.7.2:9a3ffc0492, Dec 23 2018, 22:20:52) [MSC v.1916 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> seq="""GCATAGTGTGCACAATCGCATACACCTTCTGAACAACAATGGCTTCCTTCAAGTCTTTTCTTCTCTTAGC
... CCTACTGGCAATTGTCTCAGAGGCTGCACCACCGGGACATGCTTCCCATGGAGAAGCCGACTCCAAGTGT
... CCCCTAATGGTAAAAGTATTGGATGCAGTGAGAGGAATCCCCGCTGCCAATCTGCTAGTGAACGTTTTCA
... GGCAGACTGAAAGTGGAAAGTGGGAGCAGATCACTAGTGGAAAAACCACCGAGCTTGGAGAAATCCATAA
... TCTCACTACAGATGAGCAATTCACAGAAGGAGTCTACAAAATTGAATTTGCAACAAAGGCTTTCTGGGGA
... AAACTTGGCCTCTCTCCCTTCCATGAATACGTTGATGTGGTGTTCACAGCTAATGATGCCGGACATCGTC
... AGTACACTATTGCTGTTCTGCTCACCCCCTACTCCTTCTCATCCACTGCTATTGTCAGTGAACCACACGA
... TGATCTGTAATGAAATTAAATTTCTCTTTTACCGACTCTTTTGACTGATTATGTGCGCATAATACACAGT
... GTTTTTTAACTAACATTATTGTTTTTTAATCTTTTGAAACTTCCTCCAGTCTATTTCTAGGTTATGTTAA
... CCACTGCCAAATAAACCTCTTCTGAAACAAAAAAAAAAAAAAAAAA
... """
>>> A=T=C=G=0
>>> for w in seq:
...     if w=="A":
...             A+=1
...     if w=="T":
...             T+=1
...     if w=="C":
...             C+=1
...     if w=="G":
...             G+=1
...
>>> A
199
>>> T
194
>>> C
159
>>> G
124
>>> import re
>>> pattern=r"ATG"
>>>
>>> ite=re.finditer(pattern,seq)
>>> for match in ite:
...     print(match.group(),match.start())
...
ATG 38
ATG 109
ATG 118
ATG 148
ATG 164
ATG 295
ATG 377
ATG 389
ATG 407
ATG 410
ATG 506
ATG 547
ATG 631

>>> len(seq)
686
>>> pattern2=r"CG"
>>> ite2=re.finditer(pattern2,seq)
>>> for i in ite2:
...     print(i.group(),i.start())
...
CG 103
CG 128
CG 183
CG 204
CG 262
CG 384
CG 414
CG 421
CG 493
CG 529
CG 552
>>>